name: AzureARMDeploy

on:
  push:
    branches:
      - main
      - branchnm

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show current Azure subscription
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Current Azure Subscription:"
            az account show

      - name: Create Resource Group if not exists
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name rg-azure111 --location eastus

      - name: Register Microsoft.Storage provider
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az provider register --namespace Microsoft.Storage

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: "870dd7f7-c668-401f-8d00-0ed203e30b26"
          resourceGroupName: rg-azure111
          template: ARMTemplates/storageaccount.json
         
          