name: AzureARMDeploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show current Azure subscription
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Current Azure Subscription:"
            az account show

      - name: Create Resource Group if not exists
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name rg-azure --location eastus

      - name: Register Microsoft.Storage provider
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az provider register --namespace Microsoft.Storage

      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          azcliversion: 2.72.0
          inlineScript: |
            az deployment group create \
              --name StorageAccountDeployment \
              --resource-group rg-azure \
              --template-file ARMTemplates/storageaccount.json \
              --parameters storageAccountName=sanikastorageacct123 storageAccountType=Standard_GRS
             